spring:
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/loja_ms
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
